[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
viaIR = true
solc_version = "0.8.20"

[coverage]
include = [
  "src/core/UniswapV2Factory.sol",
  "src/core/UniswapV2Pair.sol",
  "src/periphery/UniswapV2Router02.sol"
]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/QJMgczQPSqgTL8p5YHMhx_OBxt70gU-w"
fork_url = "$SEPOLIA_RPC_URL"

